### ISSUE TITLE
[1.18.2] Quarry mining into the FTB chunks

### ISSUE THREAD

**Issue by Sayaniku** [McJtyMods/RFToolsBuilder#120]
So, i see when i wake up this morning on another discord some person is griefing with your builder to the claimed FTB Chunks and they break all of the structures and replace everything with lava on public server, and ruin the gameplay of some person, personnaly i just disabled the craft of the builder for skipping that but that really anoying
https://media.discordapp.net/attachments/1180211580017836144/1187053739798966333/image.png

**Comment by McJty** [comment]
That means FTB chunk isn't configured correctly. Fake players should not be allowed to interact with claimed chunks. Not something that I can fix

**Comment by Sayaniku** [comment]
Yeah but we needed to use the fake player for another mod, and they has nothing on the config to change that

**Comment by McJty** [comment]
Well that's bad luck. There is really nothing I can do. The Builder is a fake player. I have no other way to interact with ftb claims

**Comment by McJty** [comment]
Note that the builder uses another fake player. So can't you filter on specific fake players with ftb claims?

**Comment by Sayaniku** [comment]
i'll check that

**Comment by Sayaniku** [comment]
yeah i can filter that

**Comment by Sayaniku** [comment]
i see how now, thx for that and had a great day

**Comment by Sayaniku** [comment]
nvm, that doesn't work, everything is on false
https://cdn.discordapp.com/attachments/1180817668010410055/1187356185330974731/2023-12-21_12-27-04.mp4
The record is bad because i had an bad computer sorry for that

**Comment by McJty** [comment]
Best get help with the FTB Claims people. That's on their side. I never use that mod

**Comment by Sayaniku** [comment]
okay i'll check that with the devs of FTB chunks
Thx and had a great day

**Comment by desht** [comment]
Hi McJty - I'm the current FTB Chunks maintainer. Just wanted to check: the Builder fake player is named "rftools_builder", right?  And what UUID does it use?

The issue here is that a simple fake player which has the same name for all players on the server is impossible to protect against by mods like FTB Chunks, since it can't distinguish the fake player from Player A's Builder from evil griefing Player B's Builder. Meaning griefers can set up a Builder and remotely trash someone's base, even if they to protect with FTB Chunks or similar.

The only real solution is to give each Builder's fake player the same name and UUID of the owner, i.e. the player who placed down the Builder (for reference, Mekanism's Digital Miner does this, as do PNC:R Drones and both mods interact nicely with FTB Chunks protected chunks). Not sure if you have that functionality present in the Builder, though?

**Comment by McJty** [comment]
The name is indeed "rftools_builder" and the UUID is taken from the owner of the builder. So the player owner.

**Comment by desht** [comment]
Ok, thanks.  Guess I need to get in and see if I can reproduce the issue then :)

**Comment by desht** [comment]
Just to note, I did some testing and the Builder interacts correctly with FTB Chunks, refusing to mine any chunks which are protected by the chunk owner (but mining as expected when protection is removed). So I suspect a problem with setup on the OP's server.  I'll stop bothering you now :smile:

**Comment by Sayaniku** [comment]
i just maked without bypass protection and without op with one of my player on a claimed chunk with the default config on ftb chunk, the quarry can mine in every case
