### ISSUE TITLE
Error from starting game

### ISSUE THREAD

**Issue by EmirLogas** [McJtyMods/RFToolsBuilder#54]

**Comment by McJty** [comment]
Hmm that's weird. Never seen that error before. But what do you mean by attaching jar?

**Comment by EmirSagol** [comment]
this mean attach the jar at repo releases 
![resim](https://user-images.githubusercontent.com/76751818/117687696-b39a4080-b1c0-11eb-8bf2-ab03b2fe1b7c.png)

**Comment by McJty** [comment]
I will not attach the jar to the repo. One of the points of CurseForge is so that mod developers get rewards (money) from people download mods. That can't happen if I attach the jar to the repo. Also there is no problem with downloading from CurseForge is there?

And no, I don't have a solution for your problem. I've never seen that problem before. No idea what causes it. Other people don't seem to have this problem

**Comment by McJty** [comment]
Well the bug is not fixed yet. I like to keep it so that if others have it I can try to find the common thing
